In [6]:
import numpy as np
import pandas as pd

from qr_decomposition import qr_decomposition

In [27]:
%%writefile get_eigen.py
import numpy as np

def get_eigen(A, max_iterations=10000, tolerance=1e-10):
  m, n = A.shape
  assert m == n, "Matrix must be square"

  Q_total = np.eye(n)
  A_k = A.copy()

  for i in range(max_iterations):
    Q, R = qr_decomposition(A_k)
    A_k = R @ Q
    Q_total = Q_total @ Q

    off_diagonal_norm = np.sqrt(np.sum(np.tril(A_k, -1) ** 2))
    if off_diagonal_norm < tolerance:
      break

  eigenvalues = np.diag(A_k)
  eigenvectors = Q_total

  return eigenvalues, eigenvectors

Writing get_eigen.py


In [25]:
t = np.array([[1, 2, 3],
              [8, 3, -10],
              [39, 4, 1]], dtype=np.float64)

np.linalg.eig(t)

EigResult(eigenvalues=array([-11.04630087+0.j        ,   8.02315044+5.18472028j,
         8.02315044-5.18472028j]), eigenvectors=array([[ 0.28302651+0.j        , -0.08753757-0.14749575j,
        -0.08753757+0.14749575j],
       [-0.65799137+0.j        ,  0.73019231+0.j        ,
         0.73019231-0.j        ],
       [-0.69781326+0.j        , -0.43681664-0.49658089j,
        -0.43681664+0.49658089j]]))

In [23]:
get_eigen(t)

(array([-11.04630087,  17.84111529,  -1.79481442]),
 array([[-0.28302651,  0.86017713, -0.42425382],
        [ 0.65799137, -0.14769063, -0.73840019],
        [ 0.69781326,  0.48814218,  0.52418876]]))

In [26]:
get_eigen(t)

(array([-11.04630087,  17.84111529,  -1.79481442]),
 array([[ 0.28302651,  0.86017713, -0.42425382],
        [-0.65799137, -0.14769063, -0.73840019],
        [-0.69781326,  0.48814218,  0.52418876]]))