In [2]:
import pandas as pd
import numpy as np

from get_covariance_matrix import get_covariance_matrix

In [3]:
df = pd.read_csv('data.csv')

In [5]:
mat = get_covariance_matrix(df)

In [6]:
np.linalg.eigvals(mat)

array([1.29838276, 0.75827241, 1.07436197, 0.93219883, 0.98728909])

In [8]:
np.linalg.eig(mat)

EigResult(eigenvalues=array([1.29838276, 0.75827241, 1.07436197, 0.93219883, 0.98728909]), eigenvectors=array([[-0.59038329,  0.6409096 , -0.38571805,  0.28590071, -0.10082079],
       [ 0.56246494,  0.54855744, -0.31188357, -0.52463026, -0.10104281],
       [ 0.22286381, -0.43617408, -0.79972575,  0.29388571, -0.1848075 ],
       [ 0.32013518,  0.17341084,  0.33542135,  0.46633732, -0.73311948],
       [ 0.42769843,  0.260769  ,  0.04337599,  0.58239554,  0.63875468]]))

In [9]:
mat

array([[ 1.01010101, -0.16508366,  0.04531947, -0.10286083, -0.12745817],
       [-0.16508366,  1.01010101,  0.1240043 ,  0.03860081,  0.05773273],
       [ 0.04531947,  0.1240043 ,  1.01010101,  0.00861068,  0.04325191],
       [-0.10286083,  0.03860081,  0.00861068,  1.01010101,  0.01854391],
       [-0.12745817,  0.05773273,  0.04325191,  0.01854391,  1.01010101]])

In [96]:
%%writefile qr_decomposition.py
import numpy as np

def qr_decomposition(matrix: np.ndarray):
  """
  Perform QR decomposition of a given matrix using the Gram-Schmidt process.

  Args:
    matrix (np.ndarray): The matrix which has to undergo QR decomposition.

  Returns:
    Q (np.array): The orthogonal matrix Q of the decomposition.
    R (np.array): The upper triangular R of the decomposition.
  """
  mat = np.copy(matrix)
  num_cols = mat.shape[1]

  v_vectors = []
  u_vectors = []

  for i in range(num_cols):
    v_vectors.append(mat[:, i])

  for i in range(num_cols):
    if i == 0:
      u_vectors.append(v_vectors[0] / np.linalg.norm(v_vectors[0]))
    else:
      u_vector = v_vectors[i]
      for idx in range(i - 1, -1, -1):
        u_vector -= np.dot(u_vectors[idx], v_vectors[i]) * u_vectors[idx]
      u_vector /= np.linalg.norm(u_vector)
      u_vectors.append(u_vector)

  Q = np.array(u_vectors).T
  R = np.dot(Q.T, matrix)

  return Q, R

Writing qr_decomposition.py


In [75]:
mat = np.array([[2, 2, 1],
                [-2, 1, 2],
                [18, 0, 0]],
                dtype=np.float64)

In [63]:
mat

array([[ 2.,  2.,  1.],
       [-2.,  1.,  2.],
       [18.,  0.,  0.]])

In [64]:
q, r = qr_decomposition(mat)

(array([[ 0.10976426,  0.89011215, -0.44232587],
        [-0.10976426,  0.453148  ,  0.88465174],
        [ 0.98787834, -0.04855157,  0.14744196]]),
 array([[ 1.82208672e+01,  1.40864616e-17, -3.34803457e-17],
        [ 2.08166817e-16,  1.00000000e+00, -3.39460091e-17],
        [-6.10622664e-16, -3.39460091e-17,  1.00000000e+00]]))

In [69]:
q.T @ r.T

array([[ 2.        , -0.10976426,  0.98787834],
       [16.21861518,  0.453148  , -0.04855157],
       [-8.05956089,  0.88465174,  0.14744196]])

In [70]:
num_cols = mat.shape[1]

v_vectors = []
u_vectors = []

for i in range(num_cols):
  v_vectors.append(mat[:, i])

for i in range(num_cols):
  if i == 0:
    u_vectors.append(v_vectors[0] / np.linalg.norm(v_vectors[0]))
  else:
    u_vector = v_vectors[i]
    for idx in range(i - 1, -1, -1):
      u_vector -= np.dot(u_vectors[idx], v_vectors[i]) * u_vectors[idx]
    u_vector /= np.linalg.norm(u_vector)
    u_vectors.append(u_vector)

In [71]:
u_vectors

[array([ 0.10976426, -0.10976426,  0.98787834]),
 array([ 0.89011215,  0.453148  , -0.04855157]),
 array([-0.44232587,  0.88465174,  0.14744196])]

In [73]:
np.array(u_vectors).T

array([[ 0.10976426,  0.89011215, -0.44232587],
       [-0.10976426,  0.453148  ,  0.88465174],
       [ 0.98787834, -0.04855157,  0.14744196]])

In [81]:
Q.T @ mat

array([[-36.44173432, -36.44173432, -18.22086716],
       [  4.24721607,  -2.45290081,  -4.57650885],
       [ 27.69794172,  -1.57687963,  -3.48305204]])

In [74]:
mat

array([[ 2.        ,  0.89011215, -0.44232587],
       [-2.        ,  0.453148  ,  0.88465174],
       [18.        , -0.04855157,  0.14744196]])

In [80]:
mat

array([[ 2.,  2.,  1.],
       [-2.,  1.,  2.],
       [18.,  0.,  0.]])

In [85]:
mat = np.array([[2, 1],
                [2, 1],
                [1, 5]], dtype=np.float64)

In [89]:
q, r = qr_decomposition(mat)

In [92]:
q.T @ mat

array([[3.        , 3.        ],
       [0.        , 4.24264069]])